import asyncio, re
from playwright.async_api import async_playwright
URL='http://localhost:8787/'
async def main():
    async with async_playwright() as p:
        b = await p.chromium.launch()
        errs=[]
        async def ctx(w=1280,h=900): c=await b.new_context(viewport={'width':w,'height':h}); pg=await c.new_page(); pg.on('pageerror', lambda e: errs.append(str(e))); pg.on('console', lambda m: errs.append(m.text) if m.type=='error' else None); return c,pg
        async def text(pg): return await pg.inner_text('body')
        async def go(pg,h): await pg.evaluate(f"location.hash='{h}'"); await pg.wait_for_timeout(500)
        async def login(pg,email,name=''):
            await pg.goto(URL); await pg.wait_for_timeout(900); await pg.fill('input[type=email]',email)
            if name: await pg.fill('input[placeholder="Your name"]',name)
            await pg.click('button:has-text("Sign in as developer")'); await pg.wait_for_timeout(1500)
        cA,A=await ctx(); await A.goto(URL); await A.wait_for_timeout(1200)
        t=await text(A); print('ANON shows sign-in:', 'Developer sign-in' in t, '| google honest msg:', 'not configured' in t)
        await login(A,'ajay@rvce.edu.in','Ajay Kumar'); t=await text(A); print('A first login → welcome:', 'Welcome, Ajay' in t, '| hash', A.url.split('#')[-1])
        await A.click('a:has-text("Connect an account")'); await A.wait_for_timeout(800); t=await text(A)
        print('ACCOUNTS honest states:', 'Not available' in t, 'SETU_AA_CLIENT_ID' in t, 'No connections yet' in t)
        await A.click('button:has-text("Connect") >> nth=0'); await A.wait_for_timeout(400)
        await A.click('.modal button:has-text("Approve and connect")'); await A.wait_for_timeout(300); print('CONSENT enforced:', 'Tick the consent box' in (await A.inner_text('.modal')))
        await A.check('.modal input[type=checkbox]'); await A.click('.modal button:has-text("Approve and connect")'); await A.wait_for_timeout(3000); t=await text(A)
        print('DEMO connected & labelled:', 'DEMO' in t, 'Last synced' in t, '| account rows:', t.count('balance as of'))
        await go(A,'#/home'); await A.wait_for_timeout(500); t=await text(A); print('HOME demo banner + numbers:', 'Demo data.' in t, re.findall(r'Actually yours to spend\n(−?₹[\d,]+)', t)[:1])
        cB,B=await ctx(); await login(B,'priya@rvce.edu.in','Priya M'); await B.click('a:has-text("Look around first")'); await B.wait_for_timeout(800); t=await text(B); print('B empty home, no fake data:', 'nothing to show yet' in t and '₹1,50,000' not in t)
        await go(A,'#/split'); await A.locator('input[aria-label="Total paid"]').fill('4500'); await A.fill('input[placeholder*="Dinner"]','Dinner at Truffles')
        await A.fill('input[aria-label="Search registered MILO users"]','Rahul'); await A.wait_for_timeout(800); t=await text(A); print('SEARCH unregistered:', 'No registered MILO user' in t, '| invite hint:', 'full email' in t)
        await A.fill('input[aria-label="Search registered MILO users"]','rahul@rvce.edu.in'); await A.wait_for_timeout(800); await A.click('button:has-text("Invite rahul@rvce.edu.in")'); await A.wait_for_timeout(700); t=await text(A); print('INVITE created:', 'Invite created' in t, 'signin?invite=' in t)
        await A.fill('input[aria-label="Search registered MILO users"]','pri'); await A.wait_for_timeout(800); t=await text(A); print('SEARCH found verified:', 'Registered user found' in t, 'priya@rvce.edu.in' in t)
        await A.click('.picker-row'); await A.wait_for_timeout(300); t=await text(A); print('SPLIT preview 2,250 each:', t.count('₹2,250') >= 2)
        await A.click('button:has-text("Save split")'); await A.wait_for_timeout(2000); t=await text(A); print('OWE after split (Priya owes 2,250):', 'Priya' in t and '₹2,250' in t, '| url', A.url.split('#')[-1])
        await B.reload(); await B.wait_for_timeout(1500); await go(B,'#/owe'); t=await text(B); print('B sees You owe 2,250 to Ajay:', 'Ajay' in t and '₹2,250' in t)
        await go(B,'#/notifications'); t=await text(B); print('B notification about split:', 'Dinner at Truffles' in t)
        await go(B,'#/owe'); await B.click('button:has-text("Record paid") >> nth=0'); await B.wait_for_timeout(300); await B.fill('.modal .input-money input','1000'); await B.click('.modal button:has-text("Confirm")'); await B.wait_for_timeout(1500); t=await text(B); print('B partial payment → 1,250 left:', '₹1,250' in t)
        await A.reload(); await A.wait_for_timeout(1500); await go(A,'#/owe'); t=await text(A); print('A sees 1,250 remaining:', '₹1,250' in t)
        obl = await A.evaluate("fetch('/api/obligations').then(r=>r.json())"); oid = obl['obligations'][0]['id']
        r1 = await B.evaluate(f"fetch('/api/obligations/{oid}/remind',{{method:'POST'}}).then(r=>r.status)"); print('Debtor cannot send reminder → 403:', r1)
        cC,C=await ctx(); await login(C,'karan@other.edu','Karan')
        r2 = await C.evaluate(f"fetch('/api/obligations/{oid}/payments',{{method:'POST',headers:{{'Content-Type':'application/json'}},body:JSON.stringify({{amount:1}})}}).then(r=>r.status)")
        r3 = await C.evaluate("fetch('/api/accounts').then(r=>r.json()).then(j=>j.accounts.length)")
        connA = await A.evaluate("fetch('/api/connections').then(r=>r.json()).then(j=>j.connections[0].id)")
        r4 = await C.evaluate(f"fetch('/api/connections/{connA}',{{method:'DELETE'}}).then(r=>r.status)")
        r5 = await C.evaluate("fetch('/api/splits',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'x',total:100,mode:'equal',participants:[{userId:'usr_doesnotexist'}]})}).then(r=>r.status)")
        r6 = await C.evaluate("fetch('/api/connections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({providerId:'setu_aa',consent:true})}).then(r=>r.status)")
        print('Third user: pay others obligation', r2, '| own accounts only', r3, '| delete others connection', r4, '| split with unregistered id', r5, '| unconfigured provider', r6)
        anon = await b.new_context(); ap = await anon.new_page(); await ap.goto(URL); s = await ap.evaluate("fetch('/api/transactions').then(r=>r.status)"); print('Anonymous /api/transactions →', s)
        await go(A,'#/cfo'); await A.fill('input[aria-label="Ask the AI CFO"]','Who owes me money?'); await A.press('input[aria-label="Ask the AI CFO"]','Enter'); await A.wait_for_timeout(1000); t=await text(A); print('CFO uses verified obligations:', 'Priya' in t and '₹1,250' in t)
        await go(A,'#/accounts'); await A.click('button:has-text("Sync")'); await A.wait_for_timeout(2500); t=await text(A); print('SYNC ok:', 'Synced.' in t)
        A.once('dialog', lambda d: asyncio.ensure_future(d.accept()))
        await A.click('button:has-text("Disconnect")'); await A.wait_for_timeout(2000); t=await text(A); print('DISCONNECT → no connections, DEMO gone:', 'No connections yet' in t and 'DEMO' not in t)
        await go(A,'#/home'); await A.wait_for_timeout(400); t=await text(A); print('HOME back to empty state:', 'nothing to show yet' in t)
        await go(A,'#/more'); await A.click('button:has-text("Sign out") >> nth=0'); await A.wait_for_timeout(300); await A.click('.modal button:has-text("Sign out")'); await A.wait_for_timeout(1200); t=await text(A); print('LOGOUT → sign-in:', 'Developer sign-in' in t)
        s2 = await A.evaluate("fetch('/api/me').then(r=>r.status)"); print('Session revoked server-side:', s2)
        await login(A,'ajay@rvce.edu.in'); t=await text(A); print('RETURNING user → home:', A.url.endswith('#/home'), 'Welcome, Ajay' not in t)
        await go(A,'#/owe'); print('Returning user data intact:', '₹1,250' in (await text(A)))
        m,mp=await ctx(390,844); await mp.goto(URL); await mp.wait_for_timeout(1200); await mp.screenshot(path='/home/claude/v2_signin_m.png')
        await A.goto(URL+'#/accounts'); await A.wait_for_timeout(1200); await A.screenshot(path='/home/claude/v2_accounts.png')
        await B.goto(URL+'#/split'); await B.wait_for_timeout(1200); await B.fill('input[aria-label="Search registered MILO users"]','aj'); await B.wait_for_timeout(800); await B.screenshot(path='/home/claude/v2_split.png')
        print('ERRORS:', errs[:6])
        await b.close()
asyncio.run(main())
